version: '3.7'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - '/Users/silvio.machado/dev/chat-app/:/var/lib/postgres/data'
    environment:
      POSTGRES_PASSWORD: 'postgres'
  mongo:
    container_name: 'mongo'
    image: 'mongo:latest'
    volumes:
      - '/Users/silvio.machado/dev/chat-app/data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
